- name: Gather facts from hypervisor
  debugger: on_failed
  ansible.builtin.setup:
  delegate_to: '{{ vm["host"] }}'
  delegate_facts: true
  register: hypervisor_facts

- block:
  - name: Check if zvol exists
    delegate_to: '{{ vm["host"] }}'
    stat:
      path: /dev/zvol/zfs-data/vm-disk-{{ vm["name"] }}
    register: zvol_disk

  - name: Create ZFS storage sparse zvol
    delegate_to: '{{ vm["host"] }}'
    command: zfs create -s -V {{ vm["storage"] }} zfs-data/vm-disk-{{ vm["name"] }}
    when: not zvol_disk.stat.exists

  when:
    - hostvars[vm['host']]['imageStore'] == 'zfs'

- name: Create libvirt VM domain
  delegate_to: '{{ vm["host"] }}'
  virt:
    command: define
    autostart: yes
    xml: '{{ lookup("template", "templates/vms/" + vm["type"] + ".xml") }}'

- name: Start libvirt VM
  delegate_to: '{{ vm["host"] }}'
  virt:
    name: '{{ vm["name"] }}'
    state: running