- hosts: k8s-r1
  become: yes
  tasks:
    - name: Murder kubernetes
      shell: kubeadm reset -f

    - name: Cleaning up /etc/kubernetes.
      file:
        name: /etc/kubernetes
        state: absent

    - name: Cleaning up /var/lib/cni/
      file:
        name: /var/lib/cni
        state: absent

    - name: Cleaning up /var/lib/kubelet
      file:
        name: /var/lib/kubelet
        state: absent

    - name: Cleaning up /etc/cni/
      file:
        name: /etc/cni
        state: absent

    - name: Cleaning up root home.
      file:
        name: ~/.kube
        state: absent

    - name: Remove kubelet and kubeadm
      apt:
        name: 
          - kubelet
          - kubeadm
        state: absent
        update_cache: true

    - name: Reboot
      reboot: