- name: Install libvirt
  apt:
    name: 
      - libvirt-daemon-system
      - libvirt-daemon-driver-qemu
      - libvirt-daemon-driver-storage-zfs
      - dnsmasq
      - qemu-kvm
      - ovmf
      - python3-libvirt
      - python3-lxml
    state: present

- name: Remove AppArmor
  apt:
    name:
      - apparmor
    state: absent
  register: apparmor_removed

- name: Reboot after AppArmor uninstall
  reboot:
  when: apparmor_removed.changed

- name: Configure qemu with superuser privileges
  lineinfile:
    path: /etc/libvirt/qemu.conf
    line: user = "root"
    state: present

- name: Configure qemu with superuser group privileges
  lineinfile:
    path: /etc/libvirt/qemu.conf
    line: group = "root"
    state: present

- name: Enable libvirtd
  service:
    name: libvirtd
    enabled: yes
    state: started