- name: Setting up ZFS image storage pool
  virt_pool: 
    command: define
    name: zfs
    state: present
    xml: '{{ lookup("template", "storage/zfs.xml") }}'
    autostart: true

- name: Setting up LVM image storage pool
  virt_pool: 
    command: define
    name: lvm
    state: present
    xml: '{{ lookup("template", "storage/lvm.xml") }}'
    autostart: true

- name: Setting up LVM image storage pool
  virt_pool: 
    command: start
    name: lvm
    state: active
    autostart: true

- name: Setting up /mnt/bulk
  file:
    path: /mnt/bulk
    owner: nobody
    group: nogroup
    mode: 0777
    state: directory

- name: Creating bulk zfs dataset if zfs
  zfs:
    name: zfs-data/bulk
    state: present
    extra_zfs_properties:
      mountpoint: /mnt/bulk
  when: 
    - bulk_store: zfs