- name: Setting up default storage pool
  virt_pool:
    command: define
    name: default
    state: present
    xml: '{{ lookup("template", "storage/" + vmStore + ".xml") }}'
    autostart: true
  vars:
    pool_name: "default"

- name: Setting up ZFS image storage pool
  virt_pool: 
    command: define
    name: zfs
    state: present
    xml: '{{ lookup("template", "storage/zfs.xml") }}'
    autostart: true
  vars:
    pool_name: "zfs"
  when: vmStore != "zfs"

- name: Setting up LVM image storage pool
  virt_pool: 
    command: define
    name: lvm
    state: present
    xml: '{{ lookup("template", "storage/lvm.xml") }}'
  vars:
    pool_name: "lvm"
  when: vmStore != "lvm"