- name: Create /mnt/images
  file:
    path: /mnt/images
    state: directory
    mode: 0744

- name: ZFS dataset for images
  zfs:
    name: zfs-data/images
    state: present
    extra_zfs_properties:
      compression: gzip
      mountpoint: /mnt/images
  when: "imageStore == 'zfs'"

- name: Set up image storage location
  virt_pool: 
    command: define
    name: images
    state: present
    xml: '{{ lookup("file", "files/storage/images.xml") }}'
    autostart: true

- name: Download ISOs
  get_url:
    url: '{{ item["url"] }}'
    dest: '/mnt/images/{{ item["name"] }}.iso'
  with_items: '{{ images }}'