apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-drive
  labels:
    app: drive
    component: data
    backup: "false"
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: nas.fnptr.net
    path: "/mnt/labpool/media/drive"
