


- hosts: wgvpn
  become: yes
  tasks:
    - name: Copy over wgvpn wireguard configs
      copy:
        src: wgvpn/wireguard
        dest: /etc

    - name: Copy over wgvpn wireguard keys
      copy:
        src: ../secrets/wgvpn/{{inventory_hostname}}
        dest: /etc/wireguard/privkey
        mode: 0077

    - name: Copy over per-host interface configuration
      copy:
        src: wgvpn/config/network/interfaces.d/{{inventory_hostname}}
        dest: /etc/network/interfaces.d/99-wireguard
      register: wireguard_reconfigured

- hosts: wgcdn
  become: yes
  tasks:
    - name: Copy over wgcdn wireguard configs
      copy:
        src: wgcdn/wireguard
        dest: /etc

    - name: Copy over cdn wireguard keys
      copy:
        src: ../secrets/wgcdn/{{inventory_hostname}}
        dest: /etc/wireguard/privkey
        mode: 0077

    - name: Copy over per-host interface configuration
      copy:
        src: wgcdn/config/network/interfaces.d/{{inventory_hostname}}
        dest: /etc/network/interfaces.d/99-wireguard
      register: wireguard_reconfigured

- hosts: all
  become: yes
  tasks:
    - name: Remove self-peer
      blockinfile:
        path: /etc/wireguard/fixed_peers
        marker: "# {mark} {{inventory_hostname}}"
        state: absent

    - name: Restart interfaces
      shell: ifdown -a; ifup -a;
      when: wireguard_reconfigured

    - name: Disable networking sysctl flags
      sysctl: 
        name: "{{item}}"
        value: "0"
      with_items:
        - net.ipv4.ip_forward
    
    - name: Enable networking sysctl flags
      sysctl: 
        name: "{{item}}"
        value: "1"
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.ip_forward