- hosts: wgvpn
  become: yes
  tasks:
    - name: Copy over wgvpn wireguard configs
      copy:
        src: wgvpn/wireguard
        dest: /etc

    - name: Copy over wgvpn wireguard keys
      copy:
        src: ../secrets/wgvpn/{{inventory_hostname}}
        dest: /etc/wireguard/privkey
        mode: 0077

- hosts: wgcdn_workers:master.cdn.funcptr.org
  become: yes
  tasks:
    - name: Copy over wgcdn wireguard configs
      copy:
        src: wgcdn/wireguard
        dest: /etc

    - name: Copy over cdn wireguard keys
      copy:
        src: ../secrets/wgcdn/{{inventory_hostname}}
        dest: /etc/wireguard/privkey
        mode: 0077

- hosts: all
  become: yes
  tasks:
    - name: Copy over interface files
      copy:
        src: config/network/interfaces.d/{{inventory_hostname}}
        dest: /etc/network/interfaces.d/99-interfaces
      register: interfaces_reconfigured

    - name: Remove self-peer
      blockinfile:
        path: /etc/wireguard/fixed_peers
        marker: "# {mark} {{inventory_hostname}}"
        state: absent

    - name: Delete cloudinit interface configuration
      file:
        path: /etc/network/interfaces.d/50-cloud-init
        state: absent

    - name: Disable networking sysctl flags
      sysctl: 
        name: "{{item}}"
        value: "0"
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
    
    - name: Enable networking sysctl flags
      sysctl: 
        name: "{{item}}"
        value: "1"
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding

    - name: Restart interfaces
      shell: ifdown -a; ifup -a;
      when: interfaces_reconfigured.changed