- hosts: wgcdn
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name:
          - nginx
          - certbot
          - git
          - python3-certbot-nginx
        state: present

    - name: Remove default nginx site
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default
 
    - name: Copy sites to CDN target
      copy:
        src: wgcdn/config/nginx/sites-enabled
        dest: /etc/nginx

    - name: Nuke old site
      file:
        state: absent
        dest: /srv/funcptr.org

    - name: Make directory again
      file:
        state: directory
        dest: /srv/funcptr.org

    - name: Download and unarchive website
      unarchive:
        src: https://github.com/lambda-funcptr/funcptr.org/raw/master/funcptr.org.tar.gz
        remote_src: yes
        dest: /srv/funcptr.org

    - name: Enable certbot
      shell: certbot --nginx --non-interactive -d funcptr.org --agree-tos -m "{{lookup('file', '../secrets/email')}}" --no-eff-email --keep-until-expiring

    - name: Start nginx
      service:
        name: nginx
        state: restarted
        enabled: yes