- hosts: wgcdn
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name:
          - nginx
          - certbot
          - git
          - python3-certbot-nginx
          - rsync
        state: present

    - name: Remove default nginx site
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default
 
    - name: Copy sites to CDN target
      copy:
        src: wgcdn/config/nginx/sites-enabled
        dest: /etc/nginx

    - name: Make sure webroot exists.
      file:
        state: directory
        dest: /srv/funcptr.org