- hosts: wgcdn
  become: yes
  tasks:
    - name: Enable certbot
      shell: certbot --nginx --non-interactive -d funcptr.org --agree-tos -m "{{lookup('file', '../secrets/email')}}" --no-eff-email --keep-until-expiring

    - name: Start nginx
      service:
        name: nginx
        state: restarted
        enabled: yes