all:
  hosts:
    master.cdn.funcptr.org:
      ansible_host: 51.81.34.82
  children:
    wgcdn_workers:
      hosts:
        us-east-1.cdn.funcptr.org:
          ansible_host: 51.81.83.234
    wgvpn:
      hosts:
        us-east-1.wg.funcptr.org: 
          ansible_host: 51.81.82.212
  vars:
    ansible_user: debian
    ansible_python_interpreter: /usr/bin/python3