apiVersion: v1
kind: PersistentVolume
metadata:
  name: infrastructure-grafana
  labels:
    app: grafana
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.4.255.250
    path: "/mnt/labpool/k8s-volumes/infrastructure/grafana"
