apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: servers
  labels:
    app: bookstack
  name: bookstack
  namespace: media
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bookstack
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.64.0.15