apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  selector:
    matchLabels:
      app: "bookstack"
  storageClassName: openebs-sc-hdd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-db-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  selector:
    matchLabels:
      app: "bookstack"
  storageClassName: openebs-sc-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: harbor.fnptr.net/docker/linuxserver/bookstack
        ports:
        - containerPort: 80
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/New_York
        volumeMounts:
          - mountPath: /config
            name: bookstack-data
          - mountPath: /config/www/.env
            subPath: ".env"
            name: bookstack-env
      - name: mariadb
        image: harbor.fnptr.net/docker/linuxserver/mariadb
        ports:
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: MYSQL_USER
          value: "bookstack"
        - name: MYSQL_DATABASE
          value: "bookstackdb"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_PASS
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-secrets
              key: DB_PASS
        - name: TZ
          value: America/New_York
        volumeMounts:
          - mountPath: /config
            name: bookstack-db
      volumes:
      - name: bookstack-data
        persistentVolumeClaim:
          claimName: bookstack-pvc
      - name: bookstack-db
        persistentVolumeClaim:
          claimName: bookstack-db-pvc
      - name: bookstack-env
        secret:
          secretName: bookstack-secrets
          items:
          - key: ".env"
            path: ".env"