- name: Create wireguard config
  template:
    src: etc/wireguard/corenet
    dest: /etc/wireguard/corenet.conf
  register: wg_config

- name: Enable wg-quick daemon
  service:
    name: wg-quick@corenet
    state: started
    enabled: yes

- name: Restart wg-quick
  service:
    name: wg-quick@corenet
    state: restarted
  when: wg_config.changed