apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: infrastructure-ad-disk0-dv
  namespace: infrastructure
spec:
  source:
    upload: {}
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 64Gi
    storageClassName: openebs-sc-hdd