apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: services
  labels:
    app: active-directory
  name: active-directory
  namespace: infrastructure
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: 636
  selector:
    app: active-directory
  sessionAffinity: None
  type: ClusterIP