apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ad-disk-dv
  namespace: infrastructure
  labels:
    app: active-directory
spec:
  source:
    upload: {}
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 64Gi
    storageClassName: openebs-sc-ssd
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ad-vm
  namespace: infrastructure
  labels:
    app: active-directory
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        name: ad-vm
        namespace: infrastructure
        app: active-directory
    spec:
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
          - disk:
              bus: virtio
            name: ad-disk0
          interfaces:
            - bridge: {}
              name: labnet-network
        machine:
          type: ""
      networks:
        - name: labnet-network
          multus:
            networkName: network/labnet
      terminationGracePeriodSeconds: 0
      volumes:
      - name: ad-disk0
        dataVolume:
          name: ad-disk-dv