apiVersion: v1
kind: Service
metadata:
  name: discord
  labels:
    app: matrix-discord-bridge
  namespace: matrix
spec:
  ports:
  - name: matrix-discord
    port: 9005
    protocol: TCP
    targetPort: 9005
  selector:
    app: matrix-discord-bridge
  sessionAffinity: None