apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stats-cert
  namespace: stats
spec:
  secretName: stats-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - fnptr.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - stats.fnptr.net
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io