apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: services
  labels:
    app: infrastructure-ingress
  name: infrastructure-ingress
  namespace: ingress
spec:
  selector:
    app: infrastructure-ingress
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 10.8.1.0
  externalTrafficPolicy: Cluster