apiVersion: v1
kind: Service
metadata:
  name: mc-polity
  namespace: games
  labels:
    app: mc-polity
spec:
  ports:
  - port: 25565
    name: minecraft
  - port: 2222
    name: ssh
  type: LoadBalancer
  loadBalancerIP: 10.64.30.0
  selector:
    app: mc-polity