apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: plex
    meta.helm.sh/release-namespace: media
    metallb.universe.tf/address-pool: default
  labels:
    app: kube-plex
    app.kubernetes.io/managed-by: Helm
    chart: kube-plex-0.2.7
    heritage: Helm
    release: plex
  name: plex-kube-plex
  namespace: media
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: pms
    nodePort: 30699
    port: 32400
    protocol: TCP
    targetPort: pms
  - name: http
    nodePort: 31053
    port: 80
    protocol: TCP
    targetPort: pms
  - name: https
    nodePort: 32677
    port: 443
    protocol: TCP
    targetPort: 32443
  selector:
    app: kube-plex
    release: plex
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.64.0.1
