- name: Create /etc/wireguard
  file:
    path: /etc/wireguard
    state: directory

- name: Reboot if wireguard is newly installed
  reboot: {}
  when: wireguard_installed.changed

- name: Checking for wireguard key existence...
  stat:
    path: /etc/wireguard/key
  register: key

- name: Generating wireguard key
  shell: wg genkey | tee /etc/wireguard/key | wg pubkey > /etc/wireguard/{{inventory_hostname}}.pub
  when: not key.stat.exists

- name: Enforcing permissions on wireguard key
  file:
    path: /etc/wireguard/key
    mode: u+rw,g-rwx,o-rwx

- name: Fetching wireguard key from remote
  fetch:
    src: /etc/wireguard/{{inventory_hostname}}.pub
    dest: ../secrets/corenet/wireguard/{{inventory_hostname}}
    flat: yes

- name: Create wireguard config
  template:
    src: etc/wireguard/corenet
    dest: /etc/wireguard/corenet.conf
  register: wg_config

- name: Enable wg-quick daemon
  service:
    name: wg-quick@corenet
    state: started
    enabled: yes

- name: Restart wg-quick
  service:
    name: wg-quick@corenet
    state: restarted
  when: wg_config.changed