apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: servers
  labels:
    app: service-dns
  name: service-dns
  namespace: infra
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: service-dns
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.64.0.1