- hosts: wgsdn
  become: yes
  tasks:
    - name: Update all packages
      apk:
        update_cache: yes
        upgrade: yes

    - name: Make sure the fancy special proxy_arp sysctl is set.
      sysctl: 
        name: "{{item}}"
        value: '1'
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.conf.all.proxy_arp
        - net.ipv6.conf.all.proxy_arp

    - name: Install wireguard
      apk:
        name:
          - wireguard-tools
        state: present

    - name: Copy ifupdown network config
      copy:
        src: config/network/interfaces.{{inventory_hostname}}
        dest: /etc/network/interfaces
        mode: 600

- hosts: remotes
  become: yes
  tasks:
    - name: Update everything.
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install wireguard
      apt:
        name:
          - wireguard
          - resolvconf
        state: present

- hosts: all
  become: yes
  tasks:
    - name: Set forwarding
      sysctl: 
        name: "{{item}}"
        value: '1'
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding

    - name: Copy over wireguard config
      copy:
        src: config/wireguard
        dest: /etc
        mode: 600
        
    - name: Copy over wireguard template config
      template:
        src: config/wgsdn.conf
        dest: /etc/wireguard/wgsdn.conf
        mode: 600

    - name: Remove self-peer
      blockinfile:
        path: /etc/wireguard/wgsdn.conf
        marker: "# {mark} {{inventory_hostname}}"
        state: absent