apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: default-http-backend
  name: default-http-backend
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: default-http-backend
  template:
    metadata:
      labels:
        run: default-http-backend
    spec:
      containers:
      - name: default-http-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: default-http-backend
  name: default-http-backend
  namespace: ingress
spec:
  selector:
    run: default-http-backend
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 8080