apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: service-ingress
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec: 
  controller: traefik.io/ingress-controller