apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: service-ingress
  name: service-ingress-controller
  namespace: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      run: service-ingress
  template:
    metadata:
      labels:
        run: service-ingress
    spec:
      serviceAccountName: ingress-service-account
      containers:
      - name: haproxy-ingress
        image: harbor.fnptr.net/docker/haproxytech/kubernetes-ingress
        args:
          - --configmap=ingress/service-ingress-config
          - --default-backend-service=ingress/ingress-default-backend
          - --ingress.class=service-ingress
        securityContext:
          runAsUser:  1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        resources:
          requests:
            cpu: "500m"
            memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1042
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: TZ
          value: "America/New_York"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      initContainers:
        - name: sysctl
          image: busybox:musl
          command:
            - /bin/sh
            - -c
            - sysctl -w net.ipv4.ip_unprivileged_port_start=0
          securityContext:
            privileged: true