apiVersion: v1
kind: Service
metadata:
  labels:
    app: plex
  name: plex
  namespace: media
spec:
  ports:
  - name: plex
    port: 32400
    protocol: TCP
    targetPort: 32400
  - name: http
    port: 80
    protocol: TCP
    targetPort: 32400
  selector:
    app: plex
  sessionAffinity: None