apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-config
  labels:
    app: plex
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: nas.fnptr.net
    path: "/mnt/labpool/k8s-volumes/media/plex-config"