apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-data
  labels:
    app: plex
spec:
  capacity:
    storage: 1024Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.4.255.250
    path: "/mnt/labpool/media"
