- hosts: vmhosts
  become: yes
  gather_facts: false
  tasks:
    - name: Gather facts from hypervisor
      ansible.builtin.setup:

- hosts: vms
  become: yes
  gather_facts: false
  tasks:
    - include_role:
        name: 03_provision_vms
        tasks_from: "00_provision_vm.yaml"