- import_playbook: 00_metal.yaml
- import_playbook: 01_zfs.yaml
- import_playbook: 02_vmhosts.yaml
- import_playbook: 03_provision_vms.yaml
- import_playbook: 04_wireguard.yaml
- import_playbook: 05_corenet.yaml
- import_playbook: 06_edge.yaml