- hosts: masters
  become: yes
  tasks:
    - name: Downloading Flannel object file.
      get_url:
        url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
        dest: /tmp/kube-flannel.yml

    - name: Modifying Flannel object file.
      replace:
        path: /tmp/kube-flannel.yml
        regexp: '10.244.0.0\/16/'
        replace: '10.128.0.0\/16'

    - name: Installing Flannel.
      command:
        cmd: kubectl apply -f /tmp/kube-flannel.yml
    
    - name: Installing dashboard.
      command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

    - name: Creating MetalLB namespace.
      command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml

    - name: Installing MetalLB.
      command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml

    - name: One-time MetalLB secret generation.
      shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" >> metallb-secret.txt
      args:
        chdir: $HOME
        creates: metallb-secret.txt

    - name: Cleaning up Flannel config.
      file:
        name: /tmp/kube-flannel.yml
        state: absent