- hosts: all
  become: yes
  tasks:
    - name: Installing NFS & iSCSI.
      apt:
        name:
          - nfs-common
          - nfs4-acl-tools
          - open-iscsi
        state: present

    - name: Starting the iSCSI initiator.
      service:
        name: iscsid
        state: started
        enabled: yes