apiVersion: v1
kind: Service
metadata:
  labels:
    app: synapse
  name: synapse
  namespace: matrix
spec:
  externalTrafficPolicy: Local
  ports:
  - name: matrix
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: synapse
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.64.2.0