- hosts: all
  become: yes
  tasks:
    - name: Update hostname
      hostname:
        name: "{{inventory_hostname}}.fnptr.net"

- hosts: all
  vars:
    k8s_version: 1.20.4-00
  become: yes
  tasks:
    - name: Make sure each node is up to date
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install required packages
      apt:
        name:
          - bridge-utils
          - arptables
          - ebtables
          - ethtool
          - unattended-upgrades
          - apt-listchanges
        state: present

    - name: Configure unattended-upgrades
      copy:
        src: config/apt/apt.conf.d
        dest: /etc/apt/apt.conf.d/20auto-upgrades.conf

    - name: Disable multipath
      service:
        name: multipathd
        state: stopped
        enabled: no
      register: multipath_disable
    
    - name: Flush multipath to keep the block devices free.
      shell: multipath -F
      when: multipath_disable.changed

    - name: Installing Kubernetes dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - software-properties-common
        state: present

    - name: Adding Kubernetes key.
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding upstream Kubernetes repository.
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: 'kubernetes'
  
    - name: add libcontainer keys
      apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key
        state: present

    - name: add CRI-O keys
      apt_key:
        url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.20/xUbuntu_20.04/Release.key
        state: present

    - name: Add libcontainer repo
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
        state: present
        filename: 'crio'

    - name: Add CRI-O repo
      apt_repository:
        repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04/ /

    - name: Installing CRI-O.
      apt:
        name:
          - cri-o
          - cri-o-runc
        state: present
        update_cache: true

    - name: Make sure that the CRIO Config directory exists.
      file:
        path: /etc/crio/crio.conf.d
        state: directory

    - name: Configure CRIO
      copy:
        src: config/crio/crio.conf.d
        dest: /etc/crio/crio.conf.d
      register: crio_config

    - name: Start CRI-O
      service:
        name: crio
        state: started
        enabled: yes

    - name: Restart CRI-O
      service:
        name: crio
        state: restarted
      when: crio_config.changed

    - name: Installing Kubelet.
      apt:
        name: kubelet={{k8s_version}}
        state: present
        update_cache: true

    - name: Holding kubelet package.
      dpkg_selections:
        name: kubelet
        selection: hold

    - name: Unholding kubeadm package.
      dpkg_selections:
        name: kubeadm
        selection: install

    - name: Installing kubeadm.
      apt:
        name: kubeadm={{k8s_version}}
        state: present

    - name: Holding kubeadm package.
      dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Load br_netfilter
      modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay
      modprobe:
        name: overlay
        state: present
    
    - name: Enable networking sysctl flags
      sysctl: 
        name: "{{item}}"
        value: 1
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables

    - name: Disable swap
      shell: swapoff -a

    - name: Remove swap in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    
    - name: Installing NFS & iSCSI.
      apt:
        name:
          - nfs-common
          - nfs4-acl-tools
          - open-iscsi
        state: present

    - name: Starting the iSCSI initiator.
      service:
        name: iscsid
        state: started
        enabled: yes

    - name: Create .kube directory in root user directory.
      file:
        path: ~/.kube
        state: directory