- hosts: k8s-n1
  become: yes
  tasks:
    - name: Installing kubectl.
      apt:
        name: kubectl
        state: present
    
    - name: Check if cluster is already initialized
      stat:
        path: ~/.kube/cluster_initialized.txt
      register: cluster_initialized

    - name: Initialize the cluster.
      shell: | 
        kubeadm init --pod-network-cidr=10.128.0.0/16 --service-cidr=10.255.0.0/16 \
                     --cri-socket unix:///var/run/crio/crio.sock \
                     --control-plane-endpoint=k8s.fnptr.net \
                     --service-dns-domain=k8s.fnptr.net >> ~/.kube/cluster_initialized.txt
      args:
        chdir: $HOME
        creates: ~/.kube/cluster_initialized.txt
      when: not cluster_initialized.stat.exists

    - name: Copy admin.conf to remote root's kube directory.
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes

    - name: Copy admin.conf to local user's kube directory.
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        flat: yes