- hosts: wgsdn
  become: yes
  tasks:
    - name: Update all packages
      apk:
        update_cache: yes
        upgrade: yes

    - name: Make sure the fancy special proxy_arp sysctl is set.
      sysctl: 
        name: "{{item}}"
        value: '1'
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.conf.all.proxy_arp
        - net.ipv6.conf.all.proxy_arp

    - name: Install wireguard & some other tools
      apk:
        name:
          - wireguard-tools
          - unbound
          - frr
          - sudo
          - tar
        state: present
      
    - name: Copy ifupdown network config
      copy:
        src: config/network/interfaces.{{inventory_hostname}}
        dest: /etc/network/interfaces
        mode: 600

    - name: Copy ifupdown network config
      copy:
        src: config/network/gobgp.conf
        dest: /etc/network/gobgp.conf
        mode: 600
    
    - name: Copy unbound configuration
      copy:
        src: config/unbound/unbound.conf
        dest: /etc/unbound/unbound.conf
        mode: o=rwx,g=r,o=r

    - name: Copy FRR config
      copy:
        src: config/frr/daemons
        dest: /etc/frr/daemons
        mode: o=rwx,g=rw,o=r
    
    - name: Start unbound
      service:
        name: unbound
        state: restarted
        enabled: true

    - name: Start frr
      service:
        name: frr
        state: restarted
        enabled: true

    - name: Set frr config permissions
      file:
        path: /etc/frr
        recurse: yes
        mode: o=rwx,g=rw,o=r

    - name: Creating vtysh account
      user:
        name: vtysh
        shell: /usr/bin/vtysh
        password: '*'
        groups: root, frr, frrvty

    - name: Adding ansible key
      authorized_key:
        user: vtysh
        key: "{{ lookup('file', '../secrets/ansible.pub') }}"
        state: present

- hosts: wgsdn
  become: yes
  vars:
    ansible_connection: network_cli
    ansible_network_os: frr
    ansible_user: vtysh
  tasks:
    - name: Configure global BGP SDN parameters
      frr_bgp:
        config:
          bgp_as: 65000
          router_id: 10.2.0.64
          log_neighbor_changes: False
          networks:
            - prefix: 10.128.0.0
              masklen: 16
          address_family:
            - afi: ipv4
              safi: unicast
        operation: replace

    - name: Add local BGP neighbors (masters)
      frr_bgp:
        config:
          bgp_as: 65000
          neighbors:
            - neighbor: "{{hostvars[item].ansible_host}}"
              remote_as: 64512
              description: IBGP_{{hostvars[item].inventory_hostname}}
              timers:
                keepalive: 120
                holdtime: 360
              advertisement_interval: 120
        operation: merge
      with_items: "{{ groups['masters'] }}"

    - name: Add local BGP neighbors (local workers)
      frr_bgp:
        config:
          bgp_as: 65000
          neighbors:
            - neighbor: "{{hostvars[item].ansible_host}}"
              remote_as: 64512
              description: IBGP_{{hostvars[item].inventory_hostname}}
              timers:
                keepalive: 120
                holdtime: 360
              advertisement_interval: 120
        operation: merge
      with_items: "{{ groups['local_workers'] }}"

    - name: Add remote BGP neighbors
      frr_bgp:
        config:
          bgp_as: 65000
          neighbors:
            - neighbor: "{{hostvars[item].wgsdn_host}}"
              remote_as: 65064
              description: IBGP_{{hostvars[item].inventory_hostname}}
              timers:
                keepalive: 120
                holdtime: 360
              advertisement_interval: 120
        operation: merge
      with_items: "{{ groups['remote_workers'] }}"

- hosts: remote_workers
  become: yes
  tasks:
    - name: Update everything.
      apt:
        update_cache: yes
        upgrade: safe

    - name: Install wireguard
      apt:
        name:
          - wireguard
          - resolvconf
        state: present

- hosts: wgsdn:remote_workers
  become: yes
  tasks:
    - name: Set forwarding
      sysctl: 
        name: "{{item}}"
        value: '1'
        sysctl_set: yes
        state: present
      with_items:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding

    - name: Copy over wireguard config
      copy:
        src: config/wireguard
        dest: /etc
        mode: 600
        
    - name: Copy over wireguard template config
      template:
        src: config/wgsdn.conf
        dest: /etc/wireguard/wgsdn.conf
        mode: 600

    - name: Remove self-peer
      blockinfile:
        path: /etc/wireguard/wgsdn.conf
        marker: "# {mark} {{inventory_hostname}}"
        state: absent