- hosts: k8s-n1
  become: yes
  tasks:
    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_cmd
      run_once: true

- hosts: workers
  become: yes
  tasks:
    - name: Check the node is already joined
      stat:
        path: ~/.kube/cluster_join.txt
      register: joined

    - name: Join kubernetes cluster.
      shell: "{{ hostvars['k8s-n1'].joincmd.stdout }} >> ~/.kube/cluster_join.txt"
      when: not joined.stat.exists