- hosts: k8s-n1
  become: yes
  tasks:  
    - name: Copy over custom manifests
      copy:
        src: operators/manifests
        dest: /tmp

- import_playbook: operators/00_cni.yaml
- import_playbook: operators/01_dashboard.yaml
- import_playbook: operators/02_openebs.yaml
- import_playbook: operators/03_kubevirt.yaml
- import_playbook: operators/04_cert-manager.yaml

- hosts: k8s-n1
  become: yes
  tasks:
    - name: Delete custom manifests
      file:
        path: /tmp
        state: absent

    - name: Remove master taint # Purely temporary until I get more masters.
      shell: kubectl taint nodes --all node-role.kubernetes.io/master- || true
    
    - name: Reboot... k8s-n2 has some especially long boot times
      reboot:
        reboot_timeout: 6000