- hosts: k8s-n1
  become: yes
  tasks:  
    - name: Copy over custom manifests
      copy:
        src: operators/manifests
        dest: /tmp/operator-manifests

- import_playbook: operators/00_cni.yaml
- import_playbook: operators/01_dashboard.yaml
- import_playbook: operators/02_openebs.yaml
- import_playbook: operators/03_kubevirt.yaml
- import_playbook: operators/04_cert-manager.yaml

- hosts: k8s-n1
  become: yes
  tasks:
    - name: Create local registry cert location
      file:
        path: /tmp/operator-manifests
        state: absent

    - name: Remove master taint # Purely temporary until I get more masters.
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-