- hosts: k8s-n1
  become: yes
  tasks:
    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_cmd
      run_once: true

- hosts: local_workers:remote_workers
  become: yes
  tasks:
    - name: Check the node is already joined
      stat:
        path: ~/.kube/cluster_join.txt
      register: joined

    - name: Join kubernetes cluster.
      shell: "{{ hostvars['k8s-n1'].join_cmd.stdout }} >> ~/.kube/cluster_join.txt"
      when: not joined.stat.exists

- hosts: remote_workers
  become: yes
  tasks:
    - name: Copy over additional kubelet flags
      template:
        src: config/default/kubelet.remote_workers
        dest: /etc/default/kubelet

    - name: Reboot to make sure kubelet is sanely restarted
      reboot:
        reboot_timeout: 3600