- hosts: all
  become: yes
  tasks:
    - name: Create local registry cert location
      file:
        path: /etc/docker/certs.d/harbor.fnptr.net
        state: directory

    - name: Add local registry certificates.
      shell: "openssl s_client -showcerts -connect harbor.fnptr.net:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/docker/certs.d/harbor.fnptr.net/ca.crt"