apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: servers
  name: cdi-uploadproxy
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.8.255.0
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
  sessionAffinity: None