apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.fnptr.net
    path: "/mnt/labpool/media"
