apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app: "kube-state-metrics"
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
spec:
  selector:
    app: kube-state-metrics
  type: ClusterIP
  ports:
    - name: metrics-port
      port: 8080
      targetPort: 8080