- hosts: k8s-n1
  become: yes
  vars:
    cert_manager_version: "v1.2.0"
  tasks:
    - name: Check if cert-manager is already installed
      stat:
        path: ~/.kube/cert-manager.txt
      register: cert_manager_status

    - name: Setup cert-manager
      shell: |
        kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/{{cert_manager_version}}/cert-manager.yaml > ~/.kube/cert-manager.txt;
      when: not cert_manager_status.stat.exists

    - name: Patch cert-manager for split-horizon DNS
      shell: |
        kubectl -n cert-manager patch deployment cert-manager --patch-file /tmp/manifests/cert-manager-controller-patch.yaml >> ~/.kube/cert-manager.txt;
      when: not cert_manager_status.stat.exists