apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: labnet
  namespace: network
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "labnet",
            "type": "bridge",
            "bridge": "br0",
            "ipam": {}
        }'
