apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: k8s-r1-bridge
  namespace: network
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "br-k8s-r1",
            "type": "bridge",
            "bridge": "k8s-r1-bridge",
            "ipam": {}
        }'