apiVersion: v1
kind: ConfigMap
metadata:
  name: element-config
  namespace: matrix
  labels:
    app: element
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://funcptr.org",
                "server_name": "funcptr.org"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "disable_custom_urls": false,
        "disable_guests": true,
        "disable_login_language_selector": false,
        "disable_3pid_login": false,
        "brand": "Element",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/scalar/api"
        ],
        "bug_report_endpoint_url": "https://element.io/bugreports/submit",
        "defaultCountryCode": "US",
        "showLabsSettings": false,
        "features": {
            "feature_new_spinner": false
        },
        "default_federate": true,
        "default_theme": "light",
        "roomDirectory": {
            "servers": [
                "funcptr.org",
                "matrix.org"
            ]
        },
        "piwik": false,
        "enable_presence_by_hs_url": {
            "https://matrix.org": false,
            "https://matrix-client.matrix.org": false,
            "https://funcptr.org": true
        },
        "settingDefaults": {
            "breadcrumbs": true
        },
        "jitsi": {
            "preferredDomain": "jitsi.riot.im"
        }
    }