
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  namespace: matrix
  labels:
    app: element
spec:
  replicas: 1
  selector:
    matchLabels:
      app: element
  template:
    metadata:
      labels:
        app: element
    spec:
      containers:
      - name: element
        image: vectorim/element-web
        ports:
          - containerPort: 80
            name: "http"
        volumeMounts:
          - mountPath: "/app/config.json"
            subPath: "config.json"
            name: element-config-volume
      volumes:
      - name: element-config-volume
        configMap:
          name: element-config