apiVersion: v1
kind: PersistentVolume
metadata:
  name: velero-minio
  labels:
    app: minio
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: nas.fnptr.net
    path: "/mnt/labpool/s3"