apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-plex-config
spec:
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: nas.fnptr.net
    path: "/mnt/labpool/media/config"
