- hosts: all
  become: yes
  tasks:
    - name: Update cache and update system
      apt:
        update_cache: yes
        upgrade: full
      register: updated

    - name: Reboot the system if packages got updated
      reboot:
      when: updated.changed

    - name: Install required packages
      apt:
        name:
          - docker
          - docker-compose
          - nfs-common
          - python-docker
          - git
          - unzip
          - tar
        update_cache: yes
        state: present

    - name: Start docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Create image storage mount location
      file:
        name: /data
        state: directory

    - name: Make sure the image storage location is mounted
      mount:
        src: nas.fnptr.net:/mnt/labpool/docker-images
        path: /data
        state: mounted
        fstype: nfs
        opts: nfsvers=3

    - name: Fetch harbor
      unarchive:
        src: https://github.com/goharbor/harbor/releases/download/{{harbor_version}}/harbor-offline-installer-{{harbor_version}}.tgz
        dest: ~/
        remote_src: yes