- hosts: all
  become: yes
  tasks:
    - name: Clone acme.sh
      git:
        repo: "https://github.com/acmesh-official/acme.sh.git"
        dest: ~/acme.sh
        force: yes

    - name: Check for existing certs
      stat:
        path: ~/.acme.sh
      register: acme_status

    - name: Install acme.sh
      shell:
        cmd: ./acme.sh --install
        chdir: ~/acme.sh

    - name: Make sure the certs have somewhere to go
      file:
        path: /data/cert
        state: directory

    - name: Copy reload-certs.sh
      copy:
        src: config/harbor/reload-certs.sh
        dest: ~/reload-certs.sh

    - name: Issue certs via acme.sh
      shell:
        cmd: ./acme.sh --issue --dns dns_cf -d harbor.fnptr.net --log ~/acme-log
        chdir: ~/.acme.sh
      environment:
        CF_Token: "{{lookup ('file', '../secrets/cloudflare/dns-token-fnptr-net')}}"
        CF_Account_ID: "{{lookup ('file', '../secrets/cloudflare/account-id-fnptr-net')}}"
        CF_Zone_ID: "{{lookup ('file', '../secrets/cloudflare/zone-id-fnptr-net')}}"
      when: not acme_status.stat.exists

    - name: Install certs
      shell:
        cmd: | 
          ./acme.sh --install-cert -d harbor.fnptr.net \
          --cert-file /etc/harbor/server.crt \
          --key-file /etc/harbor/server.key \
          --fullchain-file /etc/harbor/fullchain.pem \
          --reloadcmd "sh /root/reload-certs.sh"
        chdir: ~/acme.sh
      when: not acme_status.stat.exists