apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-system
  labels:
    app: "prometheus"
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - name: prometheus-port
      port: 9090
      targetPort: 9090