apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-sc-ssd
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  cstorPoolCluster: ssd-cspc
  replicaCount: "2"
  cas-type: cstor