apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-sc-hdd
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  cstorPoolCluster: cspc-hdd
  replicaCount: "2"
  cas-type: cstor