- name: Install wireguard...
  apt:
    name:
      - wireguard
    state: present
    default_release: stable
  register: wireguard_installed

- name: Create /etc/wireguard
  file:
    path: /etc/wireguard
    state: directory

- name: Reboot if wireguard is newly installed
  reboot: {}
  when: wireguard_installed.changed