apiVersion: v1
kind: Service
metadata:
  name: skyblock
  namespace: games
  labels:
    app: skyblock
spec:
  ports:
  - port: 25565
    name: minecraft
  - port: 2222
    name: ssh
  type: LoadBalancer
  loadBalancerIP: 10.64.30.1
  selector:
    app: skyblock