apiVersion: v1
kind: Service
metadata:
  labels:
    app: element
  name: element
  namespace: matrix
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: element
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 10.64.2.255