apiVersion: v1
kind: Service
metadata:
  labels:
    app: active-directory
  name: ad
  namespace: infrastructure
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: 636
  selector:
    app: active-directory
  sessionAffinity: None
  type: ClusterIP