apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: services
      protocol: layer2
      addresses:
      - 10.64.0.1-10.64.255.0
    - name: internal-services
      protocol: layer2
      addresses:
      - 10.8.0.1-10.8.255.0
      auto-assign: false