apiVersion: v1
kind: Service
metadata:
  name: skyblock
  labels:
    app: skyblock
spec:
  ports:
  - port: 25565
    name: minecraft
  type: LoadBalancer
  loadBalancerIP: 10.64.3.1
  selector:
    app: skyblock